### ISSUE TITLE
Add blackName and whiteName to active games

### ISSUE THREAD

**Issue by barmettlerl** [epfl-SDP/android#186]

**Comment by alexandrepiveteau** [comment]
This should maybe be part of the refactoring planned in #153. A solution may be to expose some `Flow<Profile>` for both players in a `Match`, which could then be loaded (lazily) by the viewmodels which require access to the `Profile` of the players of a game.

In a future iteration, we could eventually use some Firebase cloud functions to persist the profile information in the documents directly, and update this information whenever a user's profile information gets changed (for instance, if a user changes their full name).

**Comment by alexandrepiveteau** [comment]
@barmettlerl can we close this task ?

**Comment by barmettlerl** [comment]
@alexandrepiveteau Yes this task can be closed
