### ISSUE TITLE
Allow user to change their profile information

### ISSUE THREAD

**Issue by Fouad-sys** [epfl-SDP/android#188]

**Comment by alexandrepiveteau** [comment]
What's the status on this task @Fouad-sys ? Can we close it ?

**Comment by Fouad-sys** [comment]
> What's the status on this task @Fouad-sys ? Can we close it ?

Yes @alexandrepiveteau, it was an old task I was initially assigned but that got switched with other tasks and done in another sprint. I can effectively close it.
