### ISSUE TITLE
Use "Custom Subjects"  in "Truth" for equivalence assertions

### ISSUE THREAD

**Issue by matt989253** [epfl-SDP/android#285]
Some objects need comparing, but contains UIDs that make using equality impossible, e.g. a `Board` of `Piece`s with UIDs.

This can be solved using custom subjects in truth (https://truth.dev/extension.html) instead of ad-hoc functions.

_Originally posted by @alexandrepiveteau in https://github.com/epfl-SDP/android/pull/283#discussion_r863177237_

**Comment by alexandrepiveteau** [comment]
A nice summary of how to implement custom Truth subjects is available in the AndroidX repository :

https://github.com/androidx/androidx/blob/015e8f2b82049319cfada1f6ff703270cb6ac327/docs/truth_guide.md
