### ISSUE TITLE
Refactoring : Notify the string change in the setter rather than a callback in `SocialScreenSate `

### ISSUE THREAD

**Issue by KurohanaJuri** [epfl-SDP/android#98]
Copy from @alexandrepiveteau comment in the issue #78 

> Prefer using a setter of the form `set(value) {}` in the implementation of `var input: String` to be notified when the text changes rather than a dedicated `onValueChange` callback.

**Comment by alexandrepiveteau** [comment]
I've discussed with @barmettlerl over Zoom about (not) using `onValueChange` in the view model implementation, so you maybe should check and discuss together how you want to proceed to handle this (and who should take care of modifying the state interface). I'll assign you both to the issue in the meantime.
